name: EditorConfig

on:
  push:
  branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        run: |
          mkdir .public
          cp -r * .public
          mv .public public